// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package Database

const TableNameRole = "role"

// Role mapped from table <role>
type Role struct {
	ID   int64  `gorm:"column:id;primaryKey" json:"id"`
	Nama string `gorm:"column:nama;not null" json:"nama"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
