// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package Database

const TableNameVendor = "vendor"

// Vendor mapped from table <vendor>
type Vendor struct {
	ID   int64  `gorm:"column:id;primaryKey" json:"id"`
	Nama string `gorm:"column:nama;not null" json:"nama"`
}

// TableName Vendor's table name
func (*Vendor) TableName() string {
	return TableNameVendor
}
