services:
  app:
    build: .
    container_name: app-navis
    ports:
      - "5000:5000"
    # environment:
    #   - DB_HOST=postgres
    #   - DB_PORT=5433
    #   - DB_USER=postgres
    #   - DB_PASSWORD=187
    #   - DB_NAME=itam
    volumes:
      - ./.env:/app/.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 187
      POSTGRES_DB: itam
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
