// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package Database

import (
	"time"
)

const TableNameDetailAsetAplikasi = "detail_aset_aplikasi"

// DetailAsetAplikasi mapped from table <detail_aset_aplikasi>
type DetailAsetAplikasi struct {
	ID                      string    `gorm:"column:id;primaryKey" json:"id"`
	NamaAplikasi            string    `gorm:"column:nama_aplikasi;not null" json:"nama_aplikasi"`
	TanggalPembuatan        time.Time `gorm:"column:tanggal_pembuatan;not null" json:"tanggal_pembuatan"`
	TanggalTerima           time.Time `gorm:"column:tanggal_terima;not null" json:"tanggal_terima"`
	LokasiServerPenyimpanan string    `gorm:"column:lokasi_server_penyimpanan;not null" json:"lokasi_server_penyimpanan"`
	TipeAplikasi            string    `gorm:"column:tipe_aplikasi;not null" json:"tipe_aplikasi"`
	LinkAplikasi            string    `gorm:"column:link_aplikasi;not null" json:"link_aplikasi"`
	SertifikasiAplikasi     string    `gorm:"column:sertifikasi_aplikasi" json:"sertifikasi_aplikasi"`
	TanggalAktif            time.Time `gorm:"column:tanggal_aktif;not null" json:"tanggal_aktif"`
	TanggalKadaluarsa       time.Time `gorm:"column:tanggal_kadaluarsa;not null" json:"tanggal_kadaluarsa"`
	AssetID                 int64     `gorm:"column:asset_id;not null" json:"asset_id"`
	VendorID                int64     `gorm:"column:vendor_id;not null" json:"vendor_id"`
}

// TableName DetailAsetAplikasi's table name
func (*DetailAsetAplikasi) TableName() string {
	return TableNameDetailAsetAplikasi
}
