// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package Database

const TableNameDivisi = "divisi"

// Divisi mapped from table <divisi>
type Divisi struct {
	ID   int64  `gorm:"column:id;primaryKey" json:"id"`
	Nama string `gorm:"column:nama;not null" json:"nama"`
}

// TableName Divisi's table name
func (*Divisi) TableName() string {
	return TableNameDivisi
}
