// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package Database

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID               int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Nip              int64     `gorm:"column:nip;not null" json:"nip"`
	Email            string    `gorm:"column:email;not null" json:"email"`
	Password         string    `gorm:"column:password;not null" json:"password"`
	JabatanID        int64     `gorm:"column:jabatan_id;not null" json:"jabatan_id"`
	DivisiID         int64     `gorm:"column:divisi_id;not null" json:"divisi_id"`
	TanggalBergabung time.Time `gorm:"column:tanggal_bergabung;not null" json:"tanggal_bergabung"`
	CreatedAt        time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at" json:"updated_at"`
	Nama             string    `gorm:"column:nama;not null" json:"nama"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
