// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package Route

import (
	"gorm.io/gorm"
	"itam/Controller"
	"itam/Repository"
	"itam/Services"
)

// Injectors from wire.go:

func barangDI(db *gorm.DB) *Controller.BarangControllerImpl {
	barangRepositoryImpl := Repository.BarangRepositoryControllerProvider(db)
	barangServiceImpl := Services.BarangServiceControllerProvider(barangRepositoryImpl)
	barangControllerImpl := Controller.BarangControllerControllerProvider(barangServiceImpl)
	return barangControllerImpl
}
